#!/usr/bin/env bash
# It launchs given functions and passes all arguments.
# Usage:
# ./script function1 arg1 arg2 arg3
set -euo pipefail

# Gets all functions
cwd="$(realpath "$(dirname "$0")")"
source "$cwd/utility"
source "$cwd/logic"


# Checks that function name is present
assert_not_empty "${1:-}" "Function name must be present"

# Checks function name existance
declare -F $1 >/dev/null || {
  error "There is no such function: $1"
}

# Launches function with arguments
$@
