#!/usr/bin/env bash
# Script contains logic functions
set -euo pipefail


# Searches script and convert to base64
get_rootfs_configure_script_base64() {
  script_filepath=$(search_file "${1:-}" "${2:-}") || return
  cat "$script_filepath" | base64 -w 0
}

# Searches valid file path. Checks:
# - /path
# - /invocation_directory/path
search_file() {
  # Gets arguments
  invocation_directory="${1:-}"
  path="${2:-}"

  assert_absolute_directory "$invocation_directory" \
    "Invocation directory must be an absolute directory"
  assert_not_empty "$path" "Path must be set"


  # Checks if path is an absolute file path
  if test_absolute_path "$path"; then
    test -f "$path" || {
      error "Path isn't a file"
    }
    echo "$path"
    exit 0
  fi


  # Checks if it's a path relative invocation directory
  hypothetical_absolute_path="$invocation_directory/$path"
  if [[ -f $hypothetical_absolute_path ]]; then
    echo "$hypothetical_absolute_path"
    exit 0
  fi

  error "There is no such file: $path"
}
