#!/usr/bin/env bash
# This file is the main start point for the project.
# Usage:
# run recipe_name
set -euo pipefail
current_script_directory="$(dirname "${BASH_SOURCE[0]}")"
source "$current_script_directory/.run/do"


# Gets build options
build_options+=(
  "$(get_rootfs_configure_option rootfs_configure_script)"
)
build_options+=(
  "$(get_kernel_options_option kernel_options)"
)
remove_empty_elements_from_array build_options


assert_docker_is_run


# Launches archlive build
build-live-image() {
  earthly --allow-privileged +live-image "${build_options[@]}"
}


# Launches docker container interactive with live image controlled by tty
launch-interactive-tty() {
  assert_not_empty "$launch_interactive_image" \
    "launch_interactive_image isn't set"
  assert_path_is_a_file "$launch_interactive_image" \
    "launch_interactive_image isn't a file"

  earthly --allow-privileged +launcher-image

  docker container run --privileged --rm -it \
    --env additional_qemu_flags=-nographic \
    -v "$(realpath "$launch_interactive_image")":/work/live.img \
    archlive/launcher
}


# Tests live image boot on qemu virtual machine
test-live-image-boot() {
  earthly --allow-privileged +test-live-image-boot
}

_run "$@"
