#!/usr/bin/env bash
# It launchs given functions and passes all arguments.
# Usage:
# ./script function1 arg1 arg2 arg3
set -euo pipefail

# Sources all functions
current_script_directory="$(dirname "${BASH_SOURCE[0]}")"
source "$current_script_directory/utility"

INVOCATION_DIRECTORY="$(pwd)"

# runs function with arguments
_run() {
  # Checks that function name is present
  assert_not_empty "${1:-}" "Function name must be present"

  # Checks function name existance
  declare -F $1 >/dev/null || {
    error "There is no such function: $1"
  }

  # Changes directory to source loader script directory.
  local source_loader_script_directory="$(dirname "${BASH_SOURCE[1]}")"
  cd "$source_loader_script_directory"

  # runs function
  $@
}
