#!/usr/bin/env bash
# Script contains utility functions
set -euo pipefail

########################################
# Asserts

assert_not_empty() {
  test -n "${1:-}" || {
    shift
    error "$@"
  }
}

assert_path_is_a_file() {
  test -f "${1:-}" || {
    shift
    error "$@"
  }
}

assert_path_is_a_directory() {
  test -d "${1:-}" || {
    shift
    error "$@"
  }
}

########################################
# Miscellanea

error() {
  echo "$@" >&2
  exit 1
}

make_absolute_path() {
  test -n "${1:-}" || {
    error "Path to check is required"
  }

  # If path is absolute
  if [[ "$1" = /* ]]; then
    echo "$1"
    return 0
  fi

  # If path is relative
  echo "$(realpath "$INVOCATION_DIRECTORY/$1")"
  return 0
}
