#!/usr/bin/env bash
# Script contains utility functions
set -euo pipefail

########################################
# Asserts

assert_not_empty() {
  test -n "${1:-}" || {
    shift
    error "$@"
  }
}

assert_path_is_a_file() {
  test -f "${1:-}" || {
    shift
    error "$@"
  }
}

assert_docker_is_run() {
  docker info > /dev/null 2>&1 || {
    error "Docker daemon isn't run"
  }
}

########################################
# Miscellanea

error() {
  echo "$@" >&2
  exit 1
}

remove_empty_elements_from_array() {
  local -n _user_array="$1"

  for i in "${!_user_array[@]}"; do
    test -n "${_user_array[$i]}" || {
      unset _user_array[$i]
    }
  done
}
