#!/usr/bin/env bash
# Script contains utility functions
set -euo pipefail

########################################
# Asserts

assert_not_empty() {
  test -n "${1:-}" || {
    shift
    error "$@"
  }
}

assert_path_is_a_file() {
  test -f "${1:-}" || {
    shift
    error "$@"
  }
}

########################################
# Miscellanea

error() {
  echo "$@" >&2
  exit 1
}
